EXPOSE 8501
WORKDIR /app
RUN pip install numpy==1.18.5
RUN pip install pandas==1.0.4
RUN pip install convertdate==2.2.1
RUN pip install LunarCalendar==0.0.9
RUN pip install holidays==0.10.2
RUN pip install matplotlib==3.2.1
RUN pip install plotly==4.8.1
RUN pip install pystan==2.19.1.1
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY . .
CMD streamlit run app.py```